/*
 * Copyright (c) 2012-2013 Open Source Community - <http://www.peerfact.org>
 * Copyright (c) 2011-2012 University of Paderborn - UPB
 * Copyright (c) 2005-2011 KOM - Multimedia Communications Lab
 *
 * This file is part of PeerfactSim.KOM.
 * 
 * PeerfactSim.KOM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * PeerfactSim.KOM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with PeerfactSim.KOM.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.peerfact.impl.analyzer.visualization2d.gnuplot;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * Writes the results of gnuplot export to a file in a simple tab-delimited
 * format.
 * 
 * @author Leo Nobach <peerfact@kom.tu-darmstadt.de>
 * 
 * @version 05/06/2011
 */
public class SimpleGnuplotFileWriter implements IResultFileWriter {

	@Override
	public void writeToFile(File f, ResultTable results) throws IOException {
		FileWriter fstream = new FileWriter(f);
		BufferedWriter out = new BufferedWriter(fstream);
		out.write("# Gnuplot chart generated by PeerfactSim.KOM Visualization\n");
		out.write("# \n");
		out.write("# Time	");
		for (Object o : results.getObjects()) {
			out.write(o.toString() + "	");
		}
		out.write("\n");

		for (int i = 0; i < results.length; i++) {
			out.write(String.valueOf(results.getTimeAt(i)));
			out.write("	");
			for (Object o : results.getObjects()) {
				out.write(results.getValueForAt(o, i));
				out.write("	");
			}
			out.write("\n");
		}

		out.close();
	}

}
